### PR TITLE
Add pre-vue (pre-rendered Vue app) boilerplate

### PR DESCRIPTION
**Pull request by mtlynch**

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Hey! Apart from adding some config to `nuxt.config.js` what else does the boilerplate do?

**Comment by mtlynch** [comment]
Thanks for reviewing!

The features are:

- Generates a sitemap
- Generates a `robots.txt`
- Supports unique `<title>` tags for each page
- Adds unique opengraph tags to each page
- Adds Google Analytics support
- Adds a favicon
- Handles 404s

If you're an experienced Vue + Nuxt developer, these features might seem trivial, but it took me several days to get all the pieces working together. The examples I found of pre-rendered Vue apps are either super basic (hello world) or extremely complicated.

The [Nuxt documentation](https://nuxtjs.org/guide/) says the best example of a pre-rendered app is the Vue site itself, which is [insanely complex](https://github.com/nuxt/nuxtjs.org).

image

It's hard for a beginner to understand how to implement common features like these without going through lots of trial and error or piecing together several tutorials.

You can see the live demo [here](https://pre-vue.web.app/).

**Comment by mtlynch** [comment]
Just wanted to follow up here. Is there any additional information I could provide to help you decide whether to accept this PR?

**Comment by dobromir-hristov** [comment]
Hey, sorry to keep you waiting. Thank you again for your contribution to this project, and the Vue ecosystem in general, and I hope you dont get mad, but I will just say it. 

Your boilerplate's essencse, from what I am seeing, is not much more than a simple nuxt config file. For what its worth, that is the entire gist of it. 
The idea of a boilerplate is to save you hours of headaches and configuration, over many files or complex logic, (like Vue's webpack setup) something which I am not sure your does.
If I am wrong, and by no means I say I am not, correct me. 

My suggestion is, write to the Nuxt folks, propose a change, tell them the docs are confusing. This way you will help everyone who reads their docs. That is a much greater good, than me publishing your repo here.

**Comment by mtlynch** [comment]
Thanks for considering it and for your candor.

**Comment by dobromir-hristov** [comment]
Post an issue in the Nuxt docs repo, explain what lead you to this boilerplate and what it fixes. Who knows, maybe they list it as an official example :)

**Pull request closed without merging**
