### PR TITLE
Add vectre to UI Libraries/CSS Frameworks

### PR DESCRIPTION
**Pull request by vatson**

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
As good as this library is, it is not a vue specific one. I will have to close this PR, sorry.

**Comment by vatson** [comment]
Hey @dobromir-hristov

The framework is completely built on Vue. What do you mean not specific?

**Comment by dobromir-hristov** [comment]
Arghh sorry, working from phone.. long story..

Sorry for the confusion, looks good.

**Comment by vatson** [comment]
Many thanks, Dobromir!

**Pull request merged**
