### PR TITLE
Adding Why Laravel will be the best fit for Vue as a backend

### PR DESCRIPTION
**Pull request by MuhaddiMu**

### CODE REVIEW

**Comment by lloydjatkinson** [comment]
The title of this PR is very with opinionated

**Comment by MuhaddiMu** [comment]
@lloydjatkinson Thanks for highlighting it. 
Any suggestions from your side so I'll update this

**Comment by dobromir-hristov** [comment]
Hey, thanks for taking your time. 

The #90 PR is also aiming at this section. I did a suggestion there, you might want to join forces with ideas and stuff, so we make it as good as we can :))

Thank you for your contribution too!

**Comment by sustained** [comment]
If you have any points I missed then feel free to share them and I can try to write about them or even send a PR to my fork's laravel branch if you'd like.

But, just... hold off for a little while, as I'm about to do a massive rewrite.

**Pull request closed without merging**
