### PR TITLE
feat: add search on documentation thanks to DocSearch

### PR DESCRIPTION
**Pull request by s-pace**
This PR enable DocSearch since vuepress is supported. You can [find details about this feature here.](https://vuepress.vuejs.org/default-theme-config/#algolia-search)

Feel free to [check out our documentation regarding our project DocSearch](https://community.algolia.com/docsearch/).

Happy to give more details.

🚀

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Hey. Thanks, but not having access to the account with the key is not the best. I will probably create one myself.

**Comment by s-pace** [comment]
Feel free to apply @dobromir-hristov and I will grant you access.

**Comment by dobromir-hristov** [comment]
Just did. Thanks again for reminding me, had forgotten about this :)

**Comment by s-pace** [comment]
Access granted @dobromir-hristov

**Pull request merged**
